# frozen_string_literal: true

require 'csv'
require 'securerandom'
require 'ffaker'

# @!group Data Anonymization Tasks
#
# Anonymizes all PII in the current CCA database. Restore a production backup
# into a lower environment, run the anonymizer, verify, then dump and share.
#
# @example Standard run
#   bundle exec rake data:anonymize
#
# @example Dry-run (preview counts without writing)
#   bundle exec rake data:anonymize DRY_RUN=true
#
# @example CI/CD pipeline (skip interactive prompt, larger batch)
#   bundle exec rake data:anonymize SKIP_CONFIRMATION=true BATCH_SIZE=2000
#
# @example Re-run on an already-anonymized database
#   bundle exec rake data:anonymize FORCE_REANONYMIZE=true SKIP_CONFIRMATION=true
#
# @example Verify after anonymization
#   bundle exec rake data:anonymize:verify
#
# @env BATCH_SIZE      [Integer] Documents per bulk_write batch (default: 1000)
# @env DRY_RUN         [Boolean] Set to 'true' to preview without writing
# @env SKIP_CONFIRMATION [Boolean] Set to 'true' to skip the YES_ANONYMIZE prompt
# @env FORCE_REANONYMIZE [Boolean] Set to 'true' to bypass the idempotency guard
# @!endgroup

namespace :data do
  desc "Anonymize all PII data in the current database (CCA). NOT safe for production."
  task :anonymize => :environment do
    anonymizer = DataAnonymizer::Runner.new(
      batch_size: (ENV['BATCH_SIZE'] || 1000).to_i,
      dry_run: ENV['DRY_RUN'] == 'true',
      force: ENV['FORCE_REANONYMIZE'] == 'true'
    )
    anonymizer.run
  end

  namespace :anonymize do
    desc "Generate a verification report confirming PII has been anonymized"
    task :verify => :environment do
      DataAnonymizer::Verifier.new.run
    end
  end
end

# CCA-specific PII anonymization module.
#
# Rewrites all PII fields in the CCA database using fake data generated by {DataAnonymizer::FakeData}.
# Not intended for production databases — enforced by {DataAnonymizer::Runner#abort_if_production!}.
#
# @note CCA does not support the Individual Market. consumer_role, resident_role,
#   VLP documents, and CURAM features are intentionally excluded from anonymization.
# @note The following fields are intentionally NOT anonymized because they do not contain PII in CCA:
#   +dba+, +fein+, +npn+.
# @note Inbox messages (Person#inbox, Organization profiles) are intentionally NOT
#   anonymized — they do not contain PII in CCA.
# @note The +history_trackers+ collection is dropped entirely because it stores raw
#   PII field values (names, SSN, DOB) as plain text in change history documents.
# @note Idempotency is enforced via a sentinel document in +data_anonymizer_runs+.
#   Pass +force: true+ (or ENV FORCE_REANONYMIZE=true) to override.
# @note Dry-run mode logs actions without writing. Pass +dry_run: true+ or ENV DRY_RUN=true.
module DataAnonymizer
  # Generates synthetic PII values using FFaker and SecureRandom.
  #
  # Re-identification is prevented by combination improbability — each attribute
  # (name, DOB, SSN, address) is independently randomized, making it negligible
  # probability the result maps to any real person. Satisfies HIPAA Safe Harbor
  # (45 CFR §164.514).
  #
  # Inbox messages are intentionally NOT anonymized (no PII in CCA inboxes).
  # FFaker seeding (+FFaker.seed = integer+) is supported but not enabled by default.
  #
  # Call as module functions: +DataAnonymizer::FakeData.first_name+
  module FakeData
    module_function

    # @return [String] random first name
    def first_name
      FFaker::Name.first_name
    end

    # @return [String] random last name
    def last_name
      FFaker::Name.last_name
    end

    # Generates a valid-format SSN string (9 digits, no dashes).
    # Avoids invalid area codes (000, 666, 900-999) per SSA rules.
    # @return [String] 9-digit numeric string
    def ssn
      area = rand(1..665)
      area = rand(667..899) if area == 666
      group = rand(1..99)
      serial = rand(1..9999)
      format('%<area>03d%<group>02d%<serial>04d', area: area, group: group, serial: serial)
    end

    # Encrypts a plain SSN string using SymmetricEncryption (same algorithm as the app).
    # @param plain_ssn [String] plain 9-digit SSN
    # @return [String] encrypted SSN ciphertext suitable for the +encrypted_ssn+ field
    def encrypt_ssn(plain_ssn)
      SymmetricEncryption.encrypt(plain_ssn.to_s.gsub(/\D/, ''))
    end

    # Generates and encrypts a fake SSN in one step.
    # @return [String] encrypted fake SSN ciphertext
    def encrypted_ssn
      encrypt_ssn(ssn)
    end

    # @return [Integer] random day offset in the range [-1095, 1095] (±3 years)
    def dob_shift_days
      rand(-1095..1095) # ±3 years
    end

    # Shifts a date of birth by +shift_days+ days, clamping to valid bounds.
    # The shifted date will never be before 1920-01-01 and never be today or in the future.
    # @param original_dob [Date] the original date of birth
    # @param shift_days [Integer, nil] days to shift; a random offset is used if nil
    # @return [Date, nil] the shifted date, or nil if +original_dob+ is nil
    def shift_dob(original_dob, shift_days: nil)
      return nil if original_dob.nil?

      shift_days ||= dob_shift_days
      new_dob = original_dob + shift_days
      new_dob = Date.new(1920, 1, 1) if new_dob.year < 1920
      new_dob = Date.today - 1 if new_dob >= Date.today
      new_dob
    end

    # @return [String] fake street address line 1 (house number + street name)
    def address_1
      "#{rand(100..9999)} #{FFaker::Address.street_name}"
    end

    # @return [String] fake city name via FFaker
    def city
      FFaker::Address.city
    end

    # @return [String] fake US ZIP code via FFaker
    def zip
      FFaker::AddressUS.zip_code
    end

    # @return [String] fake county name derived from a random FFaker city
    def county
      "#{FFaker::Address.city} County"
    end

    # @return [String] fake email address in the form +userN@example.com+
    # @param index [Integer, nil] sequence number for deterministic uniqueness; random hex suffix used if nil
    def email(index = nil)
      prefix = index ? "user#{index}" : "user#{SecureRandom.hex(4)}"
      "#{prefix}@example.com"
    end

    # @return [String] random 7-digit phone number body (no area code)
    def phone_number
      format('%07d', rand(1_000_000..9_999_999))
    end

    # @return [String] random 3-digit US area code (200–999)
    def area_code
      format('%03d', rand(200..999))
    end

    # @return [String] full 10-digit phone number (area code + number body)
    def full_phone
      "#{area_code}#{phone_number}"
    end

    # @return [String] fake company name via FFaker
    def company_name
      FFaker::Company.name
    end

    # @return [String] fake 9-digit ABA routing number (100000000–999999999).
    #   Generated values never start with 0, matching real ABA routing number format.
    def routing_number
      rand(100_000_000..999_999_999).to_s
    end

    # @return [String] random 12-character hex string used as a fake ACH account number
    def account_number
      SecureRandom.hex(6)
    end
  end

  # Orchestrates all anonymization phases across CCA Mongoid collections.
  #
  # Phases are executed in dependency order: people first (because Phase 3 reads
  # their already-anonymized values via {#build_person_values_map_for_census}),
  # then users, census members, and organizations.
  #
  # @example
  #   runner = DataAnonymizer::Runner.new(batch_size: 500)
  #   runner.run
  # rubocop:disable Metrics/ClassLength
  class Runner
    attr_reader :batch_size, :client, :db

    # @param batch_size [Integer] documents per bulk_write batch (default 1000).
    #   Larger values improve throughput at the cost of memory.
    # @param dry_run [Boolean] when true, logs actions without writing to the database.
    # @param force [Boolean] when true, skips the idempotency guard and re-anonymizes.
    def initialize(batch_size: 1000, dry_run: false, force: false)
      @batch_size = batch_size
      @dry_run = dry_run
      @force = force
      @client = Mongoid.default_client
      @db = @client.database
      @reference_date = TimeKeeper.date_of_record
    end

    # Runs all anonymization phases in dependency order.
    #
    # Phase 0 drops +history_trackers+ (contains raw PII change history).
    # Phases 1-5 process people, users, census_members, organizations, and
    # bs_organizations. Phase 6 clears PII fields in families.
    # People must run before census_members so that
    # {#build_person_values_map_for_census} can read already-anonymized values.
    #
    # @return [void]
    def run
      abort_if_production!
      check_idempotency!
      confirm_anonymization!

      log "=== Starting CCA Data Anonymization#{' (DRY RUN)' if @dry_run} ==="
      log "Database: #{db.name}"
      log "Time: #{Time.current}"
      start_time = Time.current

      stats = run_phases
      log_stats(stats, (Time.current - start_time).round(1))
      record_run_sentinel unless @dry_run
    end

    private

    # Executes all anonymization phases in dependency order and returns a stats hash.
    # @return [Hash{Symbol => Integer}]
    def run_phases
      {
        history_trackers: drop_history_trackers,
        people: anonymize_people,
        users: anonymize_users,
        census_members: anonymize_census_members,
        organizations: anonymize_organizations,
        bs_organizations: anonymize_bs_organizations,
        families: anonymize_families
      }
    end

    # Logs the per-phase record counts and total elapsed time.
    # @param stats [Hash{Symbol => Integer}]
    # @param elapsed [Float] total run time in seconds
    # @return [void]
    def log_stats(stats, elapsed)
      log "\n=== Anonymization Complete#{' (DRY RUN — no writes)' if @dry_run} (#{elapsed}s) ==="
      stats.each { |k, v| log "  #{k}: #{v} records processed" }
    end

    # Aborts (or warns in force mode) if this database has already been anonymized.
    #
    # Writes a sentinel document to the +data_anonymizer_runs+ collection on
    # successful completion. If the sentinel exists, re-running aborts unless
    # +force: true+ was passed.
    #
    # @raise [SystemExit] if already anonymized and force is false
    def check_idempotency!
      runs_collection = db[:data_anonymizer_runs]
      previous = runs_collection.find.sort('completed_at' => -1).limit(1).first
      return unless previous

      msg = "Database '#{db.name}' was already anonymized at #{previous['completed_at']} (run_id: #{previous['_id']})"
      if @force
        log "WARNING: #{msg} — proceeding anyway (FORCE_REANONYMIZE=true)"
      else
        abort("ABORT: #{msg}\nSet FORCE_REANONYMIZE=true to override.")
      end
    end

    # Records a sentinel document in +data_anonymizer_runs+ after a successful run.
    # @return [void]
    def record_run_sentinel
      db[:data_anonymizer_runs].insert_one(
        'completed_at' => Time.current,
        'database' => db.name,
        'rails_env' => Rails.env,
        'batch_size' => @batch_size
      )
      log "Sentinel recorded in data_anonymizer_runs."
    end

    # Aborts the process if the database appears to be a production database.
    # Checks both Rails.env and the database name.
    # @raise [SystemExit] always, when the guard condition is triggered
    def abort_if_production!
      return unless Rails.env.production? || db.name =~ /production/i

      abort(
        "*** SAFETY ABORT ***\n" \
        "Refusing to run anonymization.\n" \
        "Rails.env=#{Rails.env}, database=#{db.name}\n" \
        "This task must NOT run against a production database."
      )
    end

    # Prompts the operator to type YES_ANONYMIZE before proceeding.
    # Skipped when ENV['SKIP_CONFIRMATION'] == 'true' or when in dry-run mode.
    # @raise [SystemExit] if the confirmation phrase is not entered correctly
    def confirm_anonymization!
      return if ENV['SKIP_CONFIRMATION'] == 'true' || @dry_run

      puts "\nWARNING: This will IRREVERSIBLY rewrite all PII in database '#{db.name}'."
      puts "Type YES_ANONYMIZE to proceed:"
      input = $stdin.gets&.strip
      abort("Aborted.") unless input == 'YES_ANONYMIZE'
    end

    # Drops the +history_trackers+ collection, which stores raw PII field values.
    #
    # Mongoid::History records old and new values of tracked fields on every save.
    # Leaving this collection intact after anonymization exposes real names, SSNs,
    # and DOBs in the change history. Dropping the collection is the correct
    # remediation; historical audit data is not needed in a dev/staging dump.
    #
    # @return [Integer] always 0 (collection is dropped, not iterated)
    def drop_history_trackers
      if db.collection_names.include?('history_trackers')
        count = db[:history_trackers].count_documents({})
        if @dry_run
          log "\n--- Phase 0: [DRY RUN] Would drop history_trackers (#{count} documents) ---"
        else
          db[:history_trackers].drop
          log "\n--- Phase 0: Dropped history_trackers (#{count} documents) ---"
        end
      else
        log "\n--- Phase 0: history_trackers collection not present, skipping ---"
      end
      0
    end

    # Anonymizes all documents in the +people+ collection.
    #
    # DOB shifting is consistent within each family group — all family members
    # share the same +shift_days+ value derived by {#build_family_shift_map}.
    # Tribal ID is cleared. Embedded addresses, phones, and emails are replaced.
    # Plain-text +ssn+ fields (legacy) are unset.
    #
    # @return [Integer] number of people processed
    def anonymize_people
      collection = db[:people]
      total = collection.count_documents({})
      log "\n--- Phase 1: Anonymizing People (#{total}) ---"
      family_shifts = build_family_shift_map
      processed = 0

      collection.find.batch_size(batch_size).each_slice(batch_size) do |batch|
        updates = batch.map do |doc|
          shift_days = family_shifts[doc['_id']] || FakeData.dob_shift_days
          set_fields = build_person_update(doc, shift_days: shift_days)
          {
            update_one: {
              filter: { '_id' => doc['_id'] },
              update: {
                '$set' => set_fields,
                '$unset' => { 'ssn' => '' }
              }
            }
          }
        end

        if @dry_run
          log "  [DRY RUN] Would update #{updates.size} people in this batch"
        else
          collection.bulk_write(updates, ordered: false) unless updates.empty?
        end
        processed += batch.size
        log "  #{processed}/#{total} people" if (processed % (batch_size * 5)).zero? || processed >= total
      end
      processed
    end

    # Builds the Mongo +$set+ hash for a single person document.
    #
    # @param doc [Hash] raw Mongo person document
    # @param shift_days [Integer] days to shift this person's DOBs (from {#build_family_shift_map})
    # @return [Hash] Mongo update fields suitable for a +$set+ operation
    def build_person_update(doc, shift_days:)
      new_first = FakeData.first_name
      new_last  = FakeData.last_name
      fields = {
        'first_name' => new_first,
        'last_name' => new_last,
        'full_name' => "#{new_first} #{new_last}",
        'middle_name' => FakeData.first_name.first(1),
        'name_pfx' => nil,
        'name_sfx' => nil,
        'alternate_name' => nil
      }
      fields['encrypted_ssn'] = FakeData.encrypted_ssn if doc['encrypted_ssn'].present?
      fields['tribal_id']     = nil                    if doc['tribal_id'].present?
      fields.merge!(anonymize_person_dates(doc, shift_days))
      fields.merge!(anonymize_person_embedded(doc))
    end

    # Builds shifted date fields for a person document.
    # @param doc [Hash] raw person document
    # @param shift_days [Integer] days to shift
    # @return [Hash] date fields for +$set+
    def anonymize_person_dates(doc, shift_days)
      fields = {}
      fields['dob']           = FakeData.shift_dob(doc['dob'].to_date, shift_days: shift_days)           if doc['dob'].present?
      fields['date_of_death'] = FakeData.shift_dob(doc['date_of_death'].to_date, shift_days: shift_days) if doc['date_of_death'].present?
      fields
    end

    # Anonymizes embedded address, phone, and email arrays in a person document.
    # @param doc [Hash] raw person document
    # @return [Hash] embedded array fields for +$set+
    def anonymize_person_embedded(doc)
      fields = {}
      fields['addresses'] = doc['addresses'].map { |addr| anonymize_address_hash(addr) } if doc['addresses'].present?
      fields['phones']    = doc['phones'].map    { |phone| anonymize_phone_hash(phone) }  if doc['phones'].present?
      fields['emails']    = doc['emails'].map    { |email| anonymize_email_hash(email) }  if doc['emails'].present?
      fields
    end

    # Builds a map of person_id => shift_days by iterating all families.
    #
    # For each family, collects the DOBs of all linked persons and computes a
    # single shift_days value (via {#pick_group_shift_days}) that keeps every
    # person within their age band after shifting. The same shift is applied to
    # all members so relative age gaps are preserved.
    #
    # Persons not in any family receive a random individual shift during Phase 1.
    #
    # @return [Hash{BSON::ObjectId => Integer}] person _id to shift_days mapping
    def build_family_shift_map
      families_collection = db[:families]
      people_collection = db[:people]
      shift_map = {}

      families_collection.find.batch_size(batch_size).each_slice(batch_size) do |family_batch|
        family_person_ids = family_batch.map do |family|
          (family['family_members'] || []).map { |fm| fm['person_id'] }.compact
        end
        all_person_ids = family_person_ids.flatten.uniq
        next if all_person_ids.empty?

        dob_lookup = fetch_dob_lookup(people_collection, all_person_ids)
        apply_family_shifts(shift_map, family_person_ids, dob_lookup)
      end

      log "Built family shift map for #{shift_map.size} people"
      shift_map
    end

    def fetch_dob_lookup(people_collection, person_ids)
      lookup = {}
      people_collection.find('_id' => { '$in' => person_ids }).projection('_id' => 1, 'dob' => 1).each do |p|
        lookup[p['_id']] = p['dob']&.to_date
      end
      lookup
    end

    def apply_family_shifts(shift_map, family_person_ids, dob_lookup)
      family_person_ids.each do |person_ids|
        next if person_ids.empty?

        dobs = person_ids.map { |pid| dob_lookup[pid] }.compact
        shift_days = pick_group_shift_days(dobs)
        person_ids.each { |person_id| shift_map[person_id] = shift_days }
      end
    end

    # Picks a single DOB shift (in days) valid for all members of a group.
    #
    # Computes the intersection of allowed shift ranges (via {#allowed_shift_range})
    # across all supplied DOBs. Returns 0 when no common range exists.
    #
    # @param dobs [Array<Date>] dates of birth for all members in the group
    # @return [Integer] shift in days within [-1095, 1095]
    def pick_group_shift_days(dobs)
      return FakeData.dob_shift_days if dobs.empty?

      ranges = dobs.map { |dob| allowed_shift_range(dob, @reference_date) }.compact
      return FakeData.dob_shift_days if ranges.empty?

      min_shift = ranges.map(&:first).max
      max_shift = ranges.map(&:last).min
      return 0 if min_shift.nil? || max_shift.nil?
      return 0 if min_shift > max_shift

      rand(min_shift..max_shift)
    end

    # Computes the permitted DOB shift range for a single person, enforcing:
    # 1. Global bounds: 1920-01-01 minimum, yesterday maximum.
    # 2. Age-band bounds: the shifted DOB must remain in the same band —
    #    under_18 (age < 18), between_18_25 (18 <= age < 26), or over_26 (age >= 26).
    #
    # @param dob [Date] person's date of birth
    # @param reference_date [Date] system date (TimeKeeper.date_of_record)
    # @return [Array(Integer, Integer), nil] [min_shift, max_shift] or nil if no valid range
    def allowed_shift_range(dob, reference_date)
      return nil unless dob.is_a?(Date)

      band = age_band(dob, reference_date)
      min_shift = -1095
      max_shift = 1095

      # Global bounds
      min_shift = [min_shift, (Date.new(1920, 1, 1) - dob).to_i].max
      max_shift = [max_shift, (reference_date - 1 - dob).to_i].min

      # Band bounds
      cutoff_18 = reference_date - 18.years
      cutoff_26 = reference_date - 26.years

      case band
      when :under_18
        min_shift = [min_shift, (cutoff_18 + 1 - dob).to_i].max
      when :between_18_25
        min_shift = [min_shift, (cutoff_26 + 1 - dob).to_i].max
        max_shift = [max_shift, (cutoff_18 - dob).to_i].min
      when :over_26
        max_shift = [max_shift, (cutoff_26 - dob).to_i].min
      end

      return nil if min_shift > max_shift

      [min_shift, max_shift]
    end

    def age_band(dob, reference_date)
      age = age_on(dob, reference_date)
      return :under_18 if age < 18
      return :between_18_25 if age < 26

      :over_26
    end

    def age_on(dob, reference_date)
      age = reference_date.year - dob.year
      if reference_date.month < dob.month || (reference_date.month == dob.month && reference_date.day < dob.day)
        age - 1
      else
        age
      end
    end

    # Anonymizes all documents in the +users+ collection.
    #
    # Emails are deterministic (+userN@example.com+) using a sequence number.
    # The following fields are nulled: authentication_token, current_login_token,
    # identity_verified_date, idp_uuid, identity_response_code,
    # identity_final_decision_code, identity_final_decision_transaction_id,
    # identity_response_description_text.
    #
    # @return [Integer] number of users processed
    def anonymize_users
      collection = db[:users]
      total = collection.count_documents({})
      log "\n--- Phase 2: Anonymizing Users (#{total}) ---"
      processed = 0

      collection.find.batch_size(batch_size).each_slice(batch_size) do |batch|
        updates = batch.each_with_index.map do |doc, idx|
          seq = processed + idx
          {
            update_one: {
              filter: { '_id' => doc['_id'] },
              update: {
                '$set' => {
                  'email' => FakeData.email(seq),
                  'oim_id' => "anon_user#{seq}",
                  'authentication_token' => nil,
                  'current_login_token' => nil,
                  'identity_verified_date' => nil,
                  'idp_uuid' => nil,
                  'identity_response_code' => nil,
                  'identity_final_decision_code' => nil,
                  'identity_final_decision_transaction_id' => nil,
                  'identity_response_description_text' => nil
                }
              }
            }
          }
        end

        if @dry_run
          log "  [DRY RUN] Would update #{updates.size} users in this batch"
        else
          collection.bulk_write(updates, ordered: false) unless updates.empty?
        end
        processed += batch.size
        log "  #{processed}/#{total} users" if (processed % (batch_size * 5)).zero? || processed >= total
      end
      processed
    end

    # Anonymizes all documents in the +census_members+ collection.
    #
    # For main-app +CensusEmployee+ documents that carry an +employee_role_id+,
    # the already-anonymized Person values (name, DOB, SSN) written in Phase 1
    # are copied directly from the people collection via
    # {#build_person_values_map_for_census}. This ensures that the same individual
    # has identical fake identifiers in both +people+ and +census_members+.
    #
    # For +BenefitSponsors::CensusMembers::CensusEmployee+ documents (no
    # +employee_role_id+), fresh fake values are generated independently.
    #
    # Embedded +census_dependents+ receive the same DOB shift as their parent
    # employee so that age gaps within a family group are preserved.
    #
    # @note CCA Individual Market is disabled. +consumer_role+, +resident_role+,
    #   and VLP documents are not present for census members and are not processed.
    # @note +dba+, +fein+, and +npn+ are never touched by this phase.
    # @return [Integer] number of census member documents processed
    def anonymize_census_members
      collection = db[:census_members]
      total = collection.count_documents({})
      log "\n--- Phase 3: Anonymizing Census Members (#{total}) ---"
      person_sync_map = build_person_values_map_for_census
      processed = 0

      collection.find.batch_size(batch_size).each_slice(batch_size) do |batch|
        updates = batch.map do |doc|
          employee_role_id = doc['employee_role_id']
          person_vals = employee_role_id ? person_sync_map[employee_role_id] : nil

          shift_days = census_member_shift_days(doc, person_vals)
          set_fields = build_census_member_update(doc, shift_days: shift_days, person_vals: person_vals)

          if doc['census_dependents'].present?
            set_fields['census_dependents'] = doc['census_dependents'].map do |dep|
              anonymize_census_dependent_hash(dep, shift_days: shift_days)
            end
          end

          {
            update_one: {
              filter: { '_id' => doc['_id'] },
              update: {
                '$set' => set_fields,
                '$unset' => { 'ssn' => '' }
              }
            }
          }
        end

        if @dry_run
          log "  [DRY RUN] Would update #{updates.size} census members in this batch"
        else
          collection.bulk_write(updates, ordered: false) unless updates.empty?
        end
        processed += batch.size
        log "  #{processed}/#{total} census members" if (processed % (batch_size * 5)).zero? || processed >= total
      end
      processed
    end

    # Computes the DOB shift in days to apply to a census member and its dependents.
    #
    # When linked to an already-anonymized Person, derives the shift from the delta
    # between the Person's (now fake) DOB and the census member's original DOB.
    # When no Person link exists, picks a group-consistent shift from all member DOBs.
    #
    # @param doc [Hash] raw census member document
    # @param person_vals [Hash, nil] anonymized person values from {#build_person_values_map_for_census}
    # @return [Integer] shift in days
    def census_member_shift_days(doc, person_vals)
      if person_vals && person_vals['dob'].present? && doc['dob'].present?
        (person_vals['dob'].to_date - doc['dob'].to_date).to_i
      elsif person_vals
        0
      else
        dep_dobs = (doc['census_dependents'] || []).map { |dep| dep['dob']&.to_date }.compact
        all_dobs = [doc['dob']&.to_date].compact + dep_dobs
        pick_group_shift_days(all_dobs)
      end
    end

    # Builds a map of employee_role_id => anonymized person values for census sync.
    #
    # Runs after Phase 1 has already written fake data to the people collection.
    # Queries all people that have embedded employee_roles and indexes their
    # anonymized first_name, last_name, dob, and encrypted_ssn by each
    # employee_role._id (which is what CensusEmployee.employee_role_id points to).
    #
    # Only main-app CensusEmployee documents carry employee_role_id.
    # BenefitSponsors::CensusMembers::CensusEmployee documents do not have this
    # field and will receive independently generated fake values.
    #
    # @return [Hash{BSON::ObjectId => Hash}] map from employee_role ObjectId
    #   to a hash with keys first_name, last_name, dob, encrypted_ssn
    def build_person_values_map_for_census
      map = {}
      db[:people].find(
        'employee_roles' => { '$exists' => true, '$ne' => [] }
      ).projection(
        'first_name' => 1,
        'last_name' => 1,
        'dob' => 1,
        'encrypted_ssn' => 1,
        'employee_roles._id' => 1
      ).each do |person|
        vals = {
          'first_name' => person['first_name'],
          'last_name' => person['last_name'],
          'dob' => person['dob'],
          'encrypted_ssn' => person['encrypted_ssn']
        }
        (person['employee_roles'] || []).each do |er|
          map[er['_id']] = vals
        end
      end
      log "  Built person-census sync map for #{map.size} employee roles"
      map
    end

    # Builds the Mongo +$set+ hash for a single census member document.
    #
    # When +person_vals+ is provided, the linked Person's already-anonymized
    # first_name, last_name, dob, and encrypted_ssn are used directly to ensure
    # consistency between the +people+ and +census_members+ collections.
    # When +person_vals+ is nil (no Person link), fresh fake values are generated.
    #
    # @param doc [Hash] raw Mongo census member document
    # @param shift_days [Integer] DOB shift in days; used only when +person_vals+ is nil
    # @param person_vals [Hash, nil] anonymized person fields from {#build_person_values_map_for_census}
    # @return [Hash] Mongo update fields suitable for a +$set+ operation
    def build_census_member_update(doc, shift_days:, person_vals: nil)
      if person_vals
        fields = {
          'first_name' => person_vals['first_name'],
          'last_name' => person_vals['last_name'],
          'middle_name' => nil,
          'name_sfx' => nil
        }
        fields['encrypted_ssn'] = person_vals['encrypted_ssn'] if doc['encrypted_ssn'].present? && person_vals['encrypted_ssn'].present?
        fields['dob']           = person_vals['dob']           if doc['dob'].present? && person_vals['dob'].present?
      else
        fields = {
          'first_name' => FakeData.first_name,
          'last_name' => FakeData.last_name,
          'middle_name' => nil,
          'name_sfx' => nil
        }
        fields['encrypted_ssn'] = FakeData.encrypted_ssn if doc['encrypted_ssn'].present?
        fields['dob']           = FakeData.shift_dob(doc['dob'].to_date, shift_days: shift_days) if doc['dob'].present?
      end

      fields['address'] = anonymize_address_hash(doc['address']) if doc['address'].present?

      fields['email'] = anonymize_email_hash(doc['email']) if doc['email'].present?

      fields
    end

    # Anonymizes a single census_dependent embedded hash.
    #
    # @param dep [Hash] raw census_dependent sub-document
    # @param shift_days [Integer] DOB shift in days (same value as the parent employee)
    # @return [Hash] anonymized copy of the dependent hash
    def anonymize_census_dependent_hash(dep, shift_days:)
      dep = dep.dup
      dep['first_name'] = FakeData.first_name
      dep['last_name'] = FakeData.last_name
      dep['middle_name'] = nil
      dep['name_sfx'] = nil
      dep['encrypted_ssn'] = FakeData.encrypted_ssn if dep['encrypted_ssn'].present?
      dep['dob'] = FakeData.shift_dob(dep['dob'].to_date, shift_days: shift_days) if dep['dob'].present?

      dep['address'] = anonymize_address_hash(dep['address']) if dep['address'].present?

      dep['email'] = anonymize_email_hash(dep['email']) if dep['email'].present?

      dep
    end

    # Anonymizes all documents in the legacy +organizations+ collection.
    #
    # Replaces: legal_name, broker_agency_profile ACH fields (ach_routing_number,
    # ach_account_number), and office location addresses and phones.
    #
    # @note +dba+, +fein+, and +npn+ are intentionally NOT anonymized.
    # @return [Integer] number of organization documents processed
    def anonymize_organizations
      collection = db[:organizations]
      total = collection.count_documents({})
      log "\n--- Phase 4: Anonymizing Organizations (#{total}) ---"
      processed = 0

      collection.find.batch_size(batch_size).each_slice(batch_size) do |batch|
        updates = batch.map do |doc|
          { update_one: { filter: { '_id' => doc['_id'] }, update: { '$set' => build_org_update(doc) } } }
        end

        if @dry_run
          log "  [DRY RUN] Would update #{updates.size} organizations in this batch"
        else
          collection.bulk_write(updates, ordered: false) unless updates.empty?
        end
        processed += batch.size
        log "  #{processed}/#{total} organizations" if (processed % (batch_size * 5)).zero? || processed >= total
      end
      processed
    end

    # Builds the +$set+ hash for a single legacy organization document.
    # Anonymizes legal_name, broker ACH fields, and office location addresses/phones.
    # @param doc [Hash] raw organization document
    # @return [Hash] fields for +$set+
    def build_org_update(doc)
      set_fields = { 'legal_name' => FakeData.company_name }

      if doc['broker_agency_profile'].present?
        bap = doc['broker_agency_profile'].dup
        bap['ach_routing_number'] = FakeData.routing_number if bap['ach_routing_number'].present?
        bap['ach_account_number'] = FakeData.account_number if bap['ach_account_number'].present?
        set_fields['broker_agency_profile'] = bap
      end

      set_fields['office_locations'] = anonymize_office_locations(doc['office_locations']) if doc['office_locations'].present?
      set_fields
    end

    # Replaces addresses and phones in an array of office_location sub-documents.
    # @param locations [Array<Hash>] raw office_locations array
    # @return [Array<Hash>] anonymized copies
    def anonymize_office_locations(locations)
      locations.map do |ol|
        ol = ol.dup
        ol['address'] = anonymize_address_hash(ol['address']) if ol['address'].present?
        ol['phone']   = anonymize_phone_hash(ol['phone'])   if ol['phone'].present?
        ol
      end
    end

    # Anonymizes all documents in the +benefit_sponsors_organizations_organizations+ collection.
    #
    # Replaces: legal_name, and for each embedded profile: ACH fields
    # (ach_routing_number, ach_account_number) and office location addresses and phones.
    #
    # @note +dba+, +fein+, and +npn+ are intentionally NOT anonymized.
    # @return [Integer] number of BS organization documents processed
    def anonymize_bs_organizations
      collection = db[:benefit_sponsors_organizations_organizations]
      total = collection.count_documents({})
      return 0 if total.zero?

      log "\n--- Phase 5: Anonymizing BS Organizations (#{total}) ---"
      processed = 0

      collection.find.batch_size(batch_size).each_slice(batch_size) do |batch|
        updates = batch.map do |doc|
          set_fields = {
            'legal_name' => FakeData.company_name
          }

          set_fields['profiles'] = doc['profiles'].map { |p| anonymize_bs_profile(p) } if doc['profiles'].present?

          {
            update_one: {
              filter: { '_id' => doc['_id'] },
              update: { '$set' => set_fields }
            }
          }
        end

        if @dry_run
          log "  [DRY RUN] Would update #{updates.size} BS organizations in this batch"
        else
          collection.bulk_write(updates, ordered: false) unless updates.empty?
        end
        processed += batch.size
        log "  #{processed}/#{total} BS organizations" if (processed % (batch_size * 5)).zero? || processed >= total
      end
      processed
    end

    # Anonymizes a single BenefitSponsors organization profile sub-document.
    # Replaces ACH fields and office location addresses/phones.
    # @param profile [Hash] raw profile sub-document
    # @return [Hash] anonymized copy
    def anonymize_bs_profile(profile)
      profile = profile.dup
      profile['ach_routing_number'] = FakeData.routing_number if profile['ach_routing_number'].present?
      profile['ach_account_number'] = FakeData.account_number if profile['ach_account_number'].present?
      profile['office_locations']   = anonymize_office_locations(profile['office_locations']) if profile['office_locations'].present?
      profile
    end

    # Clears the +e_case_id+ field on all family documents.
    #
    # +e_case_id+ is a foreign key to an external eligibility case management system.
    # Leaving it intact in a shared dump creates a linkage vector: anyone with
    # access to both the eligibility system and the dump can re-identify a family.
    # We clear it by +$unset+ rather than setting nil so the field is removed entirely.
    #
    # @return [Integer] number of families processed
    def anonymize_families
      collection = db[:families]
      total = collection.count_documents('e_case_id' => { '$exists' => true, '$ne' => nil })
      log "\n--- Phase 6: Anonymizing Families (#{total} with e_case_id) ---"
      return 0 if total.zero?

      if @dry_run
        log "  [DRY RUN] Would unset e_case_id on #{total} family documents"
      else
        collection.update_many(
          { 'e_case_id' => { '$exists' => true, '$ne' => nil } },
          { '$unset' => { 'e_case_id' => '' } }
        )
        log "  Cleared e_case_id on #{total} families"
      end
      total
    end

    # Replaces address PII fields in an embedded address hash.
    # Preserves structural fields (kind, state, country_name, etc.).
    # @param addr [Hash, nil] embedded address sub-document
    # @return [Hash, nil] anonymized copy, or nil if input is nil
    def anonymize_address_hash(addr)
      return addr if addr.nil?

      addr = addr.dup
      addr['address_1'] = FakeData.address_1
      addr['address_2'] = nil
      addr['address_3'] = nil if addr.key?('address_3')
      addr['city'] = FakeData.city
      addr['zip'] = FakeData.zip
      addr['county'] = FakeData.county if addr.key?('county')
      addr
    end

    # Replaces phone PII fields in an embedded phone hash.
    # Preserves structural fields (kind, primary, country_code, etc.).
    # @param phone [Hash, nil] embedded phone sub-document
    # @return [Hash, nil] anonymized copy, or nil if input is nil
    def anonymize_phone_hash(phone)
      return phone if phone.nil?

      phone = phone.dup
      phone['area_code'] = FakeData.area_code
      phone['number'] = FakeData.phone_number
      phone['full_phone_number'] = "#{phone['area_code']}#{phone['number']}"
      phone['extension'] = nil
      phone
    end

    # Replaces the email address in an embedded email hash.
    # Preserves structural fields (kind, etc.).
    # @param email_hash [Hash, nil] embedded email sub-document
    # @return [Hash, nil] anonymized copy, or nil if input is nil
    def anonymize_email_hash(email_hash)
      return email_hash if email_hash.nil?

      email_hash = email_hash.dup
      email_hash['address'] = FakeData.email
      email_hash
    end

    def log(msg)
      puts msg unless Rails.env.test?
      Rails.logger.info("[DataAnonymizer] #{msg}")
    end
  end
  # rubocop:enable Metrics/ClassLength

  # Samples the database after anonymization and produces a pass/fail report.
  #
  # Checks each anonymized collection for signs of residual PII:
  #   - Real email domains (anything not matching +@example.com+)
  #   - Plain-text +ssn+ fields
  #   - Non-nil +idp_uuid+, +tribal_id+, or +e_case_id+
  #   - Non-nil RIDP transaction IDs or session tokens
  #   - ACH routing numbers that are not exactly 9 digits
  #   - Presence of the +history_trackers+ collection (should have been dropped)
  #   - Cross-model consistency: Person vs CensusEmployee first_name for linked records
  #
  # Writes a CSV report to +tmp/anonymization_report_YYYYMMDD.csv+.
  #
  # @note +dba+, +fein+, and +npn+ are not checked — they are intentionally unchanged.
  class Verifier
    GENERATED_EMAIL_PATTERN = /@example\.com\z/
    SAMPLE_SIZE = 5000

    def initialize
      @client = Mongoid.default_client
      @db = @client.database
    end

    def run
      log "=== CCA Anonymization Verification Report ==="
      log "Database: #{@db.name}"
      log "Time: #{Time.current}"

      results    = collect_check_results
      all_passed = results.all? { |r| r[:passed] }
      report_path = write_csv_report(results)
      log_summary(results)

      if all_passed
        log "\nSTATUS: PASS - All checks passed. Safe to dump and share."
      else
        log "\nSTATUS: FAIL - Some checks failed. Review issues above."
      end

      log "Report written to: #{report_path}"
    end

    private

    # Runs all verification checks and returns the results array.
    # @return [Array<Hash>]
    def collect_check_results
      [
        check_history_trackers,
        check_people,
        check_users,
        check_census_members,
        check_organizations,
        check_bs_organizations,
        check_families,
        check_census_person_consistency
      ]
    end

    # Writes the results array to a dated CSV in tmp/ and returns the path.
    # @param results [Array<Hash>]
    # @return [String] path to the written CSV file
    def write_csv_report(results)
      report_dir  = File.join(Rails.root, 'tmp')
      FileUtils.mkdir_p(report_dir)
      report_path = File.join(report_dir, "anonymization_report_#{Date.today.strftime('%Y%m%d')}.csv")
      CSV.open(report_path, 'w') do |csv|
        csv << %w[collection total_records passed issues sample_values]
        results.each { |r| csv << [r[:collection], r[:total], r[:passed], r[:issues], r[:samples]] }
      end
      report_path
    end

    # Logs the pass/fail summary table to stdout and Rails logger.
    # @param results [Array<Hash>]
    # @return [void]
    def log_summary(results)
      log "\n--- Summary ---"
      results.each do |r|
        status = r[:passed] ? 'PASS' : 'FAIL'
        log "  #{r[:collection].ljust(55)} #{r[:total].to_s.rjust(8)} records | #{status} | #{r[:issues]}"
      end
    end

    def check_people
      collection = @db[:people]
      total = collection.count_documents({})
      issues = []

      real_email_count = 0
      collection.find.limit(SAMPLE_SIZE).each do |doc|
        (doc['emails'] || []).each do |em|
          addr = em['address']
          real_email_count += 1 if addr.present? && !addr.match?(GENERATED_EMAIL_PATTERN)
        end
      end
      issues << "#{real_email_count} real emails in sample of #{SAMPLE_SIZE}" if real_email_count > 0

      plain_ssn_count = collection.count_documents('ssn' => { '$exists' => true })
      issues << "#{plain_ssn_count} records with plain-text 'ssn' field" if plain_ssn_count > 0

      tribal_count = collection.count_documents('tribal_id' => { '$ne' => nil, '$exists' => true })
      issues << "#{tribal_count} records with non-nil tribal_id" if tribal_count > 0

      sample = collection.find.limit(3).to_a
      sample_names = sample.map { |d| "#{d['first_name']} #{d['last_name']}" }.join(", ")

      build_result("People (people)", total, issues, sample_names)
    end

    def check_history_trackers
      if @db.collection_names.include?('history_trackers')
        count = @db[:history_trackers].count_documents({})
        issues = ["history_trackers collection still exists with #{count} documents — contains raw PII change history"]
        build_result("History Trackers (history_trackers)", count, issues, "")
      else
        build_result("History Trackers (history_trackers)", 0, [], "dropped")
      end
    end

    def check_users
      collection = @db[:users]
      total = collection.count_documents({})
      issues = []

      real_email_count = 0
      collection.find.limit(SAMPLE_SIZE).each do |doc|
        addr = doc['email']
        real_email_count += 1 if addr.present? && !addr.match?(GENERATED_EMAIL_PATTERN)
      end
      issues << "#{real_email_count} users with real email domains" if real_email_count > 0

      idp_count = collection.count_documents('idp_uuid' => { '$ne' => nil, '$exists' => true })
      issues << "#{idp_count} users with non-nil idp_uuid" if idp_count > 0

      ridp_count = collection.count_documents(
        'identity_final_decision_transaction_id' => { '$ne' => nil, '$exists' => true }
      )
      issues << "#{ridp_count} users with non-nil identity_final_decision_transaction_id" if ridp_count > 0

      token_count = collection.count_documents(
        'current_login_token' => { '$ne' => nil, '$exists' => true }
      )
      issues << "#{token_count} users with non-nil current_login_token" if token_count > 0

      sample = collection.find.limit(3).to_a
      sample_emails = sample.map { |d| d['email'] }.join(", ")

      build_result("Users (users)", total, issues, sample_emails)
    end

    def check_census_members
      collection = @db[:census_members]
      total = collection.count_documents({})
      issues = []

      plain_ssn_count = collection.count_documents('ssn' => { '$exists' => true })
      issues << "#{plain_ssn_count} records with plain-text 'ssn' field" if plain_ssn_count > 0

      dep_ssn_count = collection.count_documents('census_dependents.ssn' => { '$exists' => true })
      issues << "#{dep_ssn_count} records with plain-text dependent 'ssn'" if dep_ssn_count > 0

      sample = collection.find.limit(3).to_a
      sample_names = sample.map { |d| "#{d['first_name']} #{d['last_name']}" }.join(", ")

      build_result("Census Members (census_members)", total, issues, sample_names)
    end

    def check_organizations
      collection = @db[:organizations]
      total = collection.count_documents({})
      issues = []

      ach_count = collection.count_documents(
        '$or' => [
          { 'broker_agency_profile.ach_routing_number' => { '$exists' => true, '$ne' => nil } },
          { 'broker_agency_profile.ach_account_number' => { '$exists' => true, '$ne' => nil } }
        ]
      )
      if ach_count > 0
        sample_ach = collection.find('broker_agency_profile.ach_routing_number' => { '$exists' => true }).limit(5).to_a
        real_ach = sample_ach.count do |doc|
          rn = doc.dig('broker_agency_profile', 'ach_routing_number')
          rn.present? && rn.length != 9
        end
        issues << "#{real_ach} orgs with suspicious ACH routing numbers" if real_ach > 0
      end

      sample = collection.find.limit(3).to_a
      sample_names = sample.map { |d| d['legal_name'] }.join(", ")

      build_result("Organizations (organizations)", total, issues, sample_names)
    end

    def check_families
      collection = @db[:families]
      total = collection.count_documents({})
      issues = []

      e_case_count = collection.count_documents('e_case_id' => { '$exists' => true, '$ne' => nil })
      issues << "#{e_case_count} families with non-nil e_case_id" if e_case_count > 0

      build_result("Families (families)", total, issues, "")
    end

    # Checks cross-model PII consistency between people and census_members.
    #
    # Samples up to SAMPLE_SIZE census_members that carry an +employee_role_id+
    # and verifies that +first_name+ matches the linked Person's +first_name+.
    # A mismatch indicates the Phase 1 → Phase 3 person-sync failed for some
    # documents.
    #
    # Uses a single +$in+ query to load all matched Person documents rather than
    # one query per census member, avoiding an N+1 pattern at scale.
    #
    # When no linked census members are found (e.g. on a staging environment
    # populated only with BenefitSponsors records), a warning is logged but the
    # check is not marked as FAIL — the absence of links is valid in that context.
    def check_census_person_consistency
      issues = []
      mismatches = 0
      checked = 0

      census_sample = @db[:census_members].find(
        'employee_role_id' => { '$exists' => true }
      ).limit(SAMPLE_SIZE).to_a

      role_ids = census_sample.map { |ce| ce['employee_role_id'] }.compact.uniq

      if role_ids.empty?
        log "  WARN: check_census_person_consistency — no census members with employee_role_id found in sample; skipping consistency check"
        return build_result("Cross-model: Census ↔ Person (sample 0)", 0, [], "skipped — no linked records")
      end

      person_map = {}
      @db[:people].find(
        'employee_roles._id' => { '$in' => role_ids }
      ).projection('first_name' => 1, 'employee_roles._id' => 1).each do |person|
        (person['employee_roles'] || []).each do |er|
          person_map[er['_id']] = person['first_name']
        end
      end

      census_sample.each do |ce|
        er_id = ce['employee_role_id']
        next unless person_map.key?(er_id)

        checked += 1
        mismatches += 1 if ce['first_name'] != person_map[er_id]
      end

      issues << "#{mismatches}/#{checked} linked census members have first_name mismatch with Person" if mismatches > 0

      build_result("Cross-model: Census ↔ Person (sample #{checked})", checked, issues, "")
    end

    def check_bs_organizations
      collection = @db[:benefit_sponsors_organizations_organizations]
      total = collection.count_documents({})
      return build_result("BS Organizations (benefit_sponsors_organizations_organizations)", 0, [], "") if total.zero?

      issues = []

      real_ach_count = 0
      collection.find('profiles.ach_routing_number' => { '$exists' => true }).limit(SAMPLE_SIZE).each do |doc|
        (doc['profiles'] || []).each do |profile|
          rn = profile['ach_routing_number']
          real_ach_count += 1 if rn.present? && rn.length != 9
        end
      end
      issues << "#{real_ach_count} profiles with suspicious ACH routing numbers" if real_ach_count > 0

      sample = collection.find.limit(3).to_a
      sample_names = sample.map { |d| d['legal_name'] }.join(", ")

      build_result("BS Organizations (benefit_sponsors_organizations_organizations)", total, issues, sample_names)
    end

    def build_result(collection_name, total, issues, samples)
      {
        collection: collection_name,
        total: total,
        passed: issues.empty?,
        issues: issues.empty? ? "None" : issues.join("; "),
        samples: samples
      }
    end

    def log(msg)
      puts msg unless Rails.env.test?
      Rails.logger.info("[DataAnonymizer::Verifier] #{msg}")
    end
  end
end
