# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 793be860cc07ec047627eb99b630d8ad2fc01d240d02541b1960e0a5531cc5ac3df3219263d9810583ec7de1f08f17b8bbbdb0efcc5c9e5c4a620c94eb1a9c8d

test:
  secret_key_base: df44173ed0a16c0d2c2f1f982cc006d44c6161e13f133892690d6b3ef9187368d5f46068a46b5c44f04fc4ae2e7b5b1993a7458bd8b1602e6c769c3ad7e078f5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
