ignore:
  - CVE-2024-21510
  # ignore security advisory https://github.com/rails/rails/security/advisories/GHSA-vfm5-rmrh-j26v which does not impact us.
  # futher information is available in the SECURITY.md file
  - CVE-2024-54133
  # Ignore security advisory https://github.com/sparklemotion/nokogiri/security/advisories/GHSA-vvfq-8hwr-qm4m
  # as it does not impact this particular application.
  # Further information available in the SECURITY.md file.
  - GHSA-vvfq-8hwr-qm4m
