Rails:
  Enabled: true

Metrics/LineLength:
  Max: 300

Style/HashSyntax:
  Enabled: false

Style/StringLiterals:
  Enabled: false

require: rubocop-rspec

# Deprecated
# Style/TrailingBlankLines:
#   Enabled: false
# AllCops:
#   RunRailsCops: true
