assertion_consumer_service_url: "<%= ENV['ASSERTION_CONSUMER_SERVICE_URL'] || 'https://'%>"
assertion_consumer_logout_service_url: "<%= ENV['ASSERTION_CONSUMER_SERVICE_LOGOUT_URL'] || 'https://' %>"
issuer: "<%= ENV['SAML_ISSUER'] || 'https://' %>"
idp_entity_id: "<%= ENV['IDP_ENTITY_ID'] || 'LocalIDP' %>"
idp_sso_target_url: "<%= ENV['IDP_SSO_TARGET_URL'] || 'https://' %>"
idp_slo_target_url: "<%= ENV['IDP_SLO_TARGET_URL'] || 'https://' %>"
idp_cert: "<%= ENV['IDP_CERTIFICATE'] || '123456' %>"
name_identifier_format: "<%= ENV['SAML_NAME_IDENTIFIER_FORMAT'] || '123456' %>"
idp_cert_fingerprint: "<%= ENV['IDP_CERT_FINGERPRINT'] || 'abcdefg' %>"
idp_cert_fingerprint_algorithm: "<%= ENV['IDP_CERT_FINGERPRINT_ALGORITHM'] || 'aes' %>"
curam_landing_page_url: "<%= ENV['LANDING_PAGE_URL'] || 'https://' %>"
saml_logout_url: "<%= ENV['LOGOUT_URL'] || 'http://localhost:3000' %>"
account_conflict_url: "<%= ENV['ACCOUNT_CONFLICT_URL'] || 'https://too_many_accounts' %>"
account_recovery_url: "<%= ENV['ACCOUNT_RECOVERY_URL'] || 'https://iam_login_url' %>"
iam_login_url: "<%= ENV['LOGIN_URL'] || 'https://iam_login_url' %>"
curam_broker_dashboard: "<%= ENV['BROKER_DASHBOARD_URL'] || 'https://' %>"
