assertion_consumer_service_url: "<%= val_or_nonprod_default(ENV['ASSERTION_CONSUMER_SERVICE_URL'], 'https://') %>"
assertion_consumer_logout_service_url: "<%= val_or_nonprod_default(ENV['ASSERTION_CONSUMER_SERVICE_LOGOUT_URL'], 'https://') %>"
issuer: "<%= val_or_nonprod_default(ENV['SAML_ISSUER'], 'https://') %>"
idp_entity_id: "<%= val_or_nonprod_default(ENV['IDP_ENTITY_ID'], 'LocalIDP') %>"
idp_sso_target_url: "<%= val_or_nonprod_default(ENV['IDP_SSO_TARGET_URL'], 'https://') %>"
idp_slo_target_url: "<%= val_or_nonprod_default(ENV['IDP_SLO_TARGET_URL'], 'https://') %>"
idp_cert: "<%= val_or_nonprod_default(ENV['IDP_CERTIFICATE'], '123456') %>"
name_identifier_format: "urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress"
idp_cert_fingerprint: "<%= val_or_nonprod_default(ENV['IDP_CERT_FINGERPRINT'], 'abcdefg') %>"
idp_cert_fingerprint_algorithm: "http://www.w3.org/2000/09/xmldsig#sha1"
curam_landing_page_url: "<%= val_or_nonprod_default(ENV['LANDING_PAGE_URL'], 'https://') %>"
saml_logout_url: "<%= val_or_nonprod_default(ENV['LOGOUT_URL'], 'http://localhost:3000') %>"
account_conflict_url: "<%= val_or_nonprod_default(ENV['ACCOUNT_CONFLICT_URL'], 'https://too_many_accounts') %>"
account_recovery_url: "<%= val_or_nonprod_default(ENV['ACCOUNT_RECOVERY_URL'], 'https://iam_login_url') %>"
iam_login_url: "<%= val_or_nonprod_default(ENV['LOGIN_URL'], 'https://iam_login_url') %>"
curam_broker_dashboard: "<%= val_or_nonprod_default(ENV['BROKER_DASHBOARD_URL'], 'https://') %>"
