site:
  subdomain: "mhc"
  domain_name: "hbxshop.org"
  home_url: "https://enroll.mhc.hbxshop.org"
  help_url: "https://mhc.hbxshop.org/help"
  faqs_url: "https://mhc.hbxshop.org/faqs"

  short_name: "Health Connector"
  byline: "The Right Place for the Right Plan"
  long_name: "Massachusetts Health Connector"
  copyright_period_start: "2017"
  header_message: "The Right Place for the Right Plan"
  logo_file_name: "logo.png"


  social_media:
    facebook_url: ""

  aca_market_kinds: ["shop"]  # deprecated.  use aca:market_kinds

contact_center:
  name: "Health Connector's Customer Care Center"
  alt_name: "Health Connector Customer Service"
  phone_number: "1-855-532-5465"
  tty_number: "1-855-532-5465"
  alt_phone_number: "1-855-532-LINK"
  email_address: "info@example.com"

  mailing_address:
    name: "Massachusetts Health Connector"
    address_1: "PO Box 44018"
    address_2:
    city: "Washington"
    state: "DC"
    zip: "20026"

notices:
  mailing_address:
    address_1:
    address_2:
    city:
    state: "MA"
    zip:

aca:
  state_name: "Massachusetts"
  state_abbreviation: "MA"
  market_kinds: ["shop"]
  nationwide_markets: false
  general_agency_enabled: false

#
  qle:
    with_in_sixty_days: 60
#

  individual_market:
    monthly_enrollment_due_on: 15
    verification_outstanding_window:
      days: 0

    open_enrollment:
      benefit_year_2016:
        start_on: <%= Date.new(2016,11,1) %>
        end_on: <%= Date.new(2017,1,31) %>

      benefit_year_2017:
        start_on: <%= Date.new(2016,11,1) %>
        end_on: <%= Date.new(2017,1,31) %>

  shop_market:
    small_market_employee_count_maximum: 50
    employer_contribution_percent_minimum: 50
    employee_participation_ratio_minimum: <%= 3 / 4.0 %>
    non_owner_participation_count_minimum: 1
    binder_payment_due_on: 23

    earliest_enroll_prior_to_effective_on:
      days: -30
    latest_enroll_after_effective_on:
      days: 30
    latest_enroll_after_employee_roster_correction_on:
      days: 30

    retroactive_coverage_termination_maximum:
      days: -60

    initial_application:
      publish_due_day_of_month: 15
      earliest_start_prior_to_effective_on:
        months: -2
      appeal_period_after_application_denial:
        days: 30
      # After submitting an ineligible plan year application, time period an Employer must wait
      ineligible_period_after_application_denial:
        days: 90

    renewal_application:
      earliest_start_prior_to_effective_on:
        months: -2
      monthly_open_enrollment_end_on: 20
      publish_due_day_of_month: 15
      force_publish_day_of_month: 16
      open_enrollment:
        minimum_length:
          days: 5

    benefit_period:
      length_minimum:
        year: 1
      length_maximum:
        year: 1

    open_enrollment:
      monthly_start_on: 1
      monthly_end_on: 20

      minimum_length:
        days: 5
      maximum_length:
        months: 2

    cobra_enrollment_period:
      months: 6

    group_file:
      new_enrollment_transmit_on: 16
      update_transmit_day_of_week: "friday"

  use_simple_employer_calculation_model: false
  carrier_special_plan_identifier_namespace: "urn:MA:terms:v1:plan:super_group_id#"
  rating_areas:
    - R-MA001
    - R-MA002
    - R-MA003
    - R-MA004
    - R-MA005
    - R-MA006
    - R-MA007


paper_notice: 'paper-notices'

aptc_errors:
  effective_date_overflow: "Updates not allowed at this time. Effective Date happens to be after the Policy's life (next year) when following the 15th day rule."
  enrollment_max_smaller_than_applied: "Max Applied APTC for any Enrollment cannot be smaller than the Applied APTC."
  max_aptc_non_numeric: "Max APTC needs to be a numeric value."
  max_aptc_too_small: "Max APTC should be greater than or equal to the sum of APTC Applied for all enrollments."
  max_aptc_too_big: "Max APTC should be less than 9999.99"

#   ShopOpenEnrollmentBeginDueDayOfMonth = ShopOpenEnrollmentEndDueDayOfMonth - ShopOpenEnrollmentPeriodMinimum
#   ShopPlanYearPublishedDueDayOfMonth = ShopOpenEnrollmentBeginDueDayOfMonth
