#
# Symmetric Encryption for Ruby
#
---
# For the development and test environments the test symmetric encryption keys
# can be placed directly in the source code.
# And therefore no RSA private key is required
development:   &development_defaults
  key:         1234567890ABCDEF
  iv:          1234567890ABCDEF
  cipher_name: aes-128-cbc
  encoding: :base64
  always_add_header: true

test:
  <<: *development_defaults

# dummy values to enable assets precompilation in CI build - in deployed images, a different config file comes from a
# store accessed by k8s and overrides this one.
production:
  ciphers:
    - key: 1234567890ABCDEF
      iv: 1234567890ABCDEF
      cipher_name: aes-128-cbc
      version: 1
      encoding: :base64
      always_add_header: true
