---
registry:
  - namespace:
    - :enroll_app
    - :cca_shop_market
    features:
      - key: :automation_of_ineligible_benefit_sponsors
        item: :ineligble_benefit_sponsors_automation
        is_enabled: true
        settings:
          - key: :ineligible_employer_transmission_day_of_month
            item: 1


# EnrollRegistry.feature_enabled?(:automation_of_ineligible_benefit_sponsors)
# EnrollRegistry[:automation_of_ineligible_benefit_sponsors].setting(:ineligible_employer_transmission_day_of_month).item