---
registry:
  - namespace:
      - :features
    features:
      - key: :enroll_app
        is_enabled: true
        meta:
          label: Enroll Application
          content_type: :boolean
          default: true
          value: true
          description: The Enroll Application enables customers to register and enroll in products, including determining eligibility, shopping for products, calculating premiums, and securely managing their personal information
          is_required: true
          is_visible: true
        settings:
          - key: :copyright_period_start
            item: "2013"
          - key: :policies_url
            item: "https://dchealthlink.com/"
          - key: :faqs_url
            item: "https://www.dchealthlink.com/Frequently-Asked-Questions"
          - key: :help_url
            item: "https://www.dchealthlink.com/help"
          - key: :business_resource_center_url
            item: "https://www.mahealthconnector.org/business/business-resource-center"
          - key: :nondiscrimination_notice_url
            item: "https://www.dchealthlink.com/nondiscrimination"
          - key: :subdomain
            item: 'mhc'
          - key: :census_employees_template_file
            item: 'Health Connector - Employee Census Template'
      - key: :employee_roster_updates
        is_enabled: true
      - key: :continuous_plan_shopping
        is_enabled: true
      - key: display_estimated_employee_costs
        is_enabled: true
      - key: :admin_issuers_tab_display
        is_enabled: <%= ENV['ADMIN_ISSUERS_TAB_DISPLAY_IS_ENABLED'] || false %>
      - key: :admin_products_tab_display
        is_enabled: <%= ENV['ADMIN_PRODUCTS_TAB_DISPLAY_IS_ENABLED'] || false %>
      - key: :lock_account_for_unsuccessful_match_attempts
        item: :lock_account_for_unsuccessful_match_attempts
        is_enabled: <%= ENV['LOCK_ACCOUNT_FOR_UNSUCCESSFUL_MATCH_ATTEMPTS_IS_ENABLED'] || false %>
      - key: :employee_match_max_attempts
        item: <%= ENV['EMPLOYEE_MATCH_MAX_ATTEMPTS'] || 3 %>
        is_enabled: true
      - key: :upload_file_size_limit_in_mb
        item: <%= ENV['UPLOAD_FILE_SIZE_LIMIT_IN_MB'] || 10 %>
        is_enabled: true
      - key: :prevent_concurrent_sessions
        item: :prevent_concurrent_sessions
        is_enabled: <%= ENV['PREVENT_CONCURRENT_SESSIONS_IS_ENABLED'] || false %>
      - key: :generic_forgot_password_text
        item: :generic_forgot_password_text
        is_enabled: <%= ENV['GENERIC_FORGOT_PASSWORD_TEXT_IS_ENABLED'] || false %>
