name: Build reports image

on:
  workflow_dispatch:
    inputs:
      branch:
        default: 'master'
        description: 'Branch to build'
        required: true
      commit_sha:
        description: 'Commit short SHA to build'
        required: true
  repository_dispatch:
    types:
      - build-reports-image

concurrency:
  group: reports-${{ github.ref }}
  cancel-in-progress: true

env:
  CLIENT: cca

jobs:
  prep:
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.prep.outputs.branch}}
      commitShortSha: ${{ steps.prep.outputs.commit_sha }}
      registryGhcr: ${{ steps.prep.outputs.registry_ghcr }}
    steps:
      - name: Set variables from workflow dispatch
        id: prep
        run: |
          if [[ "${{github.event_name}}" == "repository_dispatch" ]]; then
            echo "branch=${{ github.event.client_payload.branch }}" >> $GITHUB_OUTPUT
            echo "commit_sha=${{ github.event.client_payload.commit_sha }}" >> $GITHUB_OUTPUT
          else
            echo "branch=${{ github.event.inputs.branch }}" >> $GITHUB_OUTPUT
            echo "commit_sha=${{ github.event.inputs.commit_sha }}" >> $GITHUB_OUTPUT
          fi
          echo "registry_ghcr=ghcr.io" >> $GITHUB_OUTPUT

  build-and-upload-image:
    runs-on: ubuntu-latest
    needs: [prep]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ needs.prep.outputs.branch }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          version: v0.17.1

      # Cache layers specific to current sha, but allow rummaging through older caches if none for current
# TODO determine if this would need to be fixed to actually cache seomthing (and what key should be, w/r/t not
#  destructively colliding with normal build cache, and meaningful sha (presumably sha from inputs?) or whatnot.
#      - name: Cache Docker layers
#        uses: actions/cache@v4
#        with:
#          path: /tmp/.buildx-cache
#          key: ${{ runner.os }}-buildx-${{ github.sha }}
#          restore-keys: |
#            ${{ runner.os }}-buildx

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ needs.prep.outputs.registryGhcr }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build reports Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          builder: ${{ steps.buildx.outputs.name }}
          file: .docker/Dockerfile.gha-reports
          # Example tags:
          # ghcr.io/health-connector/enroll:cca-reports tag for easier compat with existing Devops flows,
          # ghcr.io/health-connector/enroll:pv188414567_add_gha_workflow-40df5b1-cca tag for better traceability
          tags: |
            ghcr.io/health-connector/enroll:${{ env.CLIENT }}-reports
            ${{ format('{0}/{1}-{2}-reports', needs.prep.outputs.registryGhcr, needs.prep.outputs.commitShortSha, env.CLIENT) }}
          build-args: |
            CLIENT=${{ env.CLIENT }}
            COMMIT_SHORT_SHA=${{ needs.prep.outputs.commitShortSha }}
            BRANCH=${{ needs.prep.outputs.branch }}
