name: pull request checks
on:
  pull_request:

concurrency:
  group: checks-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: false
          rubygems: 3.3.26
          bundler: 2.4.22
      - name: Config git and fetch comparison branch
        run: |
          git config diff.renameLimit 800
          git fetch --no-tags --depth=1 origin ${{ github.base_ref }}
      - name: Run rubocop
        run: |
          bundle exec rubocop-git origin/${{ github.base_ref }} | tee results.txt
      - name: Evaluate results
        run: |
          cat results.txt | grep --silent "no offenses detected"
