name: pull request checks
on:
  pull_request:

concurrency:
  group: checks-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          rubygems: 3.3.26
      - run: |
          bundle exec rubocop-git origin/master > results.txt
          cat results.txt
          cat results.txt | grep "no offenses detected"
