name: Full suite check
on:
  push:
  schedule:
    - cron: "0 6 * * *"

concurrency:
  group: ruby-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true 

jobs:
  rspec:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:5.0
        ports:
          - 27017:27017
        options: >-
          --name "mongo"
          --health-cmd mongo
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    strategy:
      fail-fast: false
      matrix:
        group:
          [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20 ]
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: false
          rubygems: 3.3.26
          node-version: '12'
      - name: Restore Node Modules
        id: npm-cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-v12-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-v12-${{ hashFiles('yarn.lock') }}
      - name: Install node dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: yarn install
      - name: Install Test boosters gem
        run: gem install treye-semaphore_test_boosters --version '2.5.2'
      - name: Run tests
        run: rspec_booster --job ${{ matrix.group }}/${{ strategy.job-total }}
        env:
          RSPEC_SPLIT_CONFIGURATION_PATH: 'ci/rspec-split-config.json'
          TEST_BOOSTERS_RSPEC_TEST_FILE_PATTERN: "{spec,components/benefit_markets/spec,components/benefit_sponsors/spec,components/notifier/spec,components/sponsored_benefits/spec,components/transport_gateway/spec,components/transport_profiles/spec}/**/*_spec.rb"
          TB_RSPEC_FORMATTER: "progress"

  cucumber:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:5.0
        ports:
          - 27017:27017
        options: >-
          --name "mongo"
          --health-cmd mongo
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    strategy:
      fail-fast: false
      matrix:
        group:
          [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20 ]
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: false
          rubygems: 3.3.26
      - uses: actions/setup-node@v4
        with:
          node-version: '12'
      - name: Restore Node Modules
        id: npm-cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-v12-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-v12-${{ hashFiles('yarn.lock') }}
      - name: Install node dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: yarn install
      - name: Install Legacy Chrome
        run: |
          wget https://storage.googleapis.com/chrome-for-testing-public/131.0.6778.264/linux64/chrome-linux64.zip
          unzip chrome-linux64.zip
      - name: Install Test boosters gem
        run: gem install treye-semaphore_test_boosters --version '2.5.2'
      - name: Run tests
        env:
          WD_VERSION: "131.0.6778.264"
          WD_CHROME_PATH: ${{ github.workspace }}/chrome-linux64/chrome
        run: cucumber_booster --job ${{ matrix.group }}/${{ strategy.job-total }}